---
version: 2

references:
  docker_golang: &docker_golang
    docker:
      - image: golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /project

jobs:
  tests:
    <<: *docker_golang
    steps:
      - checkout
      - run: make promu
      - run: make build

  mod-tidy:
    <<: *docker_golang
    steps:
      - checkout
      - run: go mod tidy
      - run: go mod vendor
      - run: test -z "$(git status --porcelain)"

workflows:
  version: 2
  pipeline:
    jobs:
      - mod-tidy
      - tests
