---
name: Go
on: [push]
jobs:
  mod-tidy:
    name: mod-tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
        id: go
      - name: go mod tidy
        run: go mod tidy
      - run: |
          if ! git diff --exit-code -- go.mod go.sum; then
            echo "Modules not tidy; please run 'go mod tidy'";
          fi;
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [mod-tidy]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
        id: go
      - name: Promu
        run: make promu
      - name: Build
        run: make build
